# For now this is our docker compose file.
# To start it, move to the main folder, and run:
# docker-compose up -d --force-recreate

# SQL Server was a nightmare as UT8 doesnt convert properly over to a password in SQL Server.
# You can use SQL Server Managment or Azure Data Studio to do direct connections.
# Settings:
#   Server Name: localhost
#   Authentication: SQL Authentication
#   Login: sa
#   Password: Password1_HOLDER

version: "3.9"

services:
  db:
    container_name: LinuxMetricsCollectorDB
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - '1433:1433'