# For now this is our docker compose file.
# To start it, move to the main folder, and run:
# docker-compose up -d
#
# If you you just pulled a new version of the DB, make sure to !prune! docker
# first so it doesn't run the old DB. 
#
# SQL Server was a nightmare as UT8 doesnt convert properly 
# over to a password in SQL Server.
# You can use SQL Server Managment or Azure Data Studio to do direct connections.
# Settings:
#   Server Name: localhost --> 127.0.0.1
#   Authentication: SQL Authentication
#   Login: sa
#   Password: Password1_HOLDER

version: "3.9"

services:
  db:
    container_name: LinuxMetricsCollectorDB
    build:
      context: .
    ports:
      - '1433:1433'